POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "first_name": "Léandre",
  "last_name": "Escorneboueü",
  "username": "leandre_esc",
  "email": "leandre.esc@icloud.com",
  "password": "_Titouan33!_"
}